### ISSUE TITLE
Input Display Not Opening

### ISSUE THREAD

**Issue by TiagoGamer26** [fruityloops1/HOS-InputDisplay#1]
My input display used to work, but suddenly when I open it after `INFO: VAO: [ID 52] Mesh uploaded successfully to VRAM (GPU)` everything **stops working** and the input display just becomes a white rectangle. I've tried **re-downloading and restarting my PC and Switch**, but it still does not work.

**Comment by fruityloops1** [comment]
Every time your switch goes into sleep mode, you have to press ZR + ZL + L + R + Plus to restart the input server.

**Comment by Nin10Doug** [comment]
I've been also experiencing this issue when running the EXE file on the PC. I don't think its a switch issue. It just stays in that INFO and the program just states not responding afterwards.

**Comment by Nin10Doug** [comment]
Found the main issue
HOS-Atmosphere had the "Flags" folder named "Flag".
Probably a minor typo mistake on your end, but I got the tool running now! Works like a charm!
